### ISSUE TITLE
Make Protected field T in MonoProvider so providers can access it and update if needed 

### ISSUE THREAD

**Issue by oneclickdev** [voody2506/UniLeo-Lite#4]
https://github.com/voody2506/UniLeo-Lite/blob/35dd02d500c4dedba9f16cccbd77542cdb1f8480/Runtime/MonoHelpers/MonoProvider.cs#L10

I think it would be better to make it Protected... What do you think?

**Comment by voody2506** [comment]
Hello! Thanks you for your interest. Why Do you need this Protected access? 
Please, can you share more info about your case.

Thanks

**Comment by oneclickdev** [comment]
hi! thanks for your reply
Protected will grant me an access to struct fields in Provider so I can implement custom logic before PreInit in case I need it

**Comment by voody2506** [comment]
> hi! thanks for your reply
> Protected will grant me an access to struct fields in Provider so I can implement custom logic before PreInit in case I need it

Thanks, MonoProvider class updated with protected value access!

**Comment by voody2506** [comment]
Can I close issue ?

**Comment by oneclickdev** [comment]
yeah, thats awesome. thanks a lot!
