### ISSUE TITLE
Update package version after latest change

### ISSUE THREAD

**Issue by oneclickdev** [voody2506/UniLeo-Lite#5]
Hello Voody2506!
sorry, for bothering you) but I think it would be better to change version from 1.0.0 to 1.0.1 in Package so it can be updated by Unity Package manager automatically.. could you please? 
 https://github.com/voody2506/UniLeo-Lite/blob/36f561e417ba0ec2946d72713233ccb4c3a30f5b/package.json#L6

it is related to that change: [https://github.com/voody2506/UniLeo-Lite/issues/4](url)

**Comment by voody2506** [comment]
Hello! Thank you again 
Done
